apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 012689415038.dkr.ecr.us-east-1.amazonaws.com/coworking-space/coworkingrepo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5153
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: coworking-configmap
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: coworking-configmap
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: coworking-configmap
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: coworking-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: coworking-configmap
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking-secrets
              key: DB_PASSWORD
      restartPolicy: Always